import { showCaceSmall } from '../mascot';
import { t } from '../i18n';

export function cmdHelp(): void {
  console.log();
  showCaceSmall('');
  console.log();
  console.log('  ╔═══════════════════════════════════════════╗');
  console.log(`  ║        ${t('cmd.help.title')}             ║`);
  console.log('  ╚═══════════════════════════════════════════╝');
  console.log();
  console.log(`  ${t('cmd.help.start')}`);
  console.log(`     ${t('cmd.help.startDesc')}`);
  console.log(`     ${t('cmd.help.startTag')}`);
  console.log(`     ${t('cmd.help.startEstimate')}`);
  console.log();
  console.log(`  ${t('cmd.help.mark')}`);
  console.log(`     ${t('cmd.help.markDesc')}`);
  console.log();
  console.log(`  ${t('cmd.help.stop')}`);
  console.log(`     ${t('cmd.help.stopDesc')}`);
  console.log();
  console.log(`  ${t('cmd.help.status')}`);
  console.log(`     ${t('cmd.help.statusDesc')}`);
  console.log();
  console.log(`  ${t('cmd.help.list')}`);
  console.log(`     ${t('cmd.help.listDesc')}`);
  console.log(`     ${t('cmd.help.listToday')}`);
  console.log(`     ${t('cmd.help.listTag')}`);
  console.log(`     ${t('cmd.help.listLimit')}`);
  console.log();
  console.log(`  ${t('cmd.help.search')}`);
  console.log(`     ${t('cmd.help.searchDesc')}`);
  console.log();
  console.log(`  ${t('cmd.help.sync')}`);
  console.log(`     ${t('cmd.help.syncDesc')}`);
  console.log();
  console.log(`  ${t('cmd.help.summary')}`);
  console.log(`     ${t('cmd.help.summaryDesc')}`);
  console.log(`     ${t('cmd.help.summaryToday')}`);
  console.log(`     ${t('cmd.help.summaryWeek')}`);
  console.log(`     ${t('cmd.help.summaryMonth')}`);
  console.log(`     ${t('cmd.help.summaryTag')}`);
  console.log();
  console.log(`  ${t('cmd.help.delete')}`);
  console.log(`     ${t('cmd.help.deleteDesc')}`);
  console.log();
  console.log(`  ${t('cmd.help.resume')}`);
  console.log(`     ${t('cmd.help.resumeDesc')}`);
  console.log();
  console.log(`  ${t('cmd.help.export')}`);
  console.log(`     ${t('cmd.help.exportDesc')}`);
  console.log(`     ${t('cmd.help.exportFormat')}`);
  console.log(`     ${t('cmd.help.exportOutput')}`);
  console.log();
  console.log(`  ${t('cmd.help.pomodoro')}`);
  console.log(`     ${t('cmd.help.pomodoroDesc')}`);
  console.log(`     ${t('cmd.help.pomodoroWork')}`);
  console.log(`     ${t('cmd.help.pomodoroBreak')}`);
  console.log(`     ${t('cmd.help.pomodoroRounds')}`);
  console.log(`     ${t('cmd.help.pomodoroTag')}`);
  console.log();
  console.log(`  ${t('cmd.help.focus')}`);
  console.log(`     ${t('cmd.help.focusDesc')}`);
  console.log();
  console.log(`  ${t('cmd.help.lang')}`);
  console.log();
  console.log(`  ${t('cmd.help.help')}`);
  console.log(`     ${t('cmd.help.helpDesc')}`);
  console.log();
}
