// Adapted from CacinieP's MINT reference, 2026-09-09.
// Source and contour decisions: docs/design/mint.md.
// Art is data: no timers, terminal access or Python dependency.
export const DARK_PALETTE = {
  h: '72cbbb',
  m: '439da5',
  e: 'b2f4d5',
  p: 'dba4b1',
  s: 'e6d5c4',
  g: '82989e',
  w: 'd5e7e3',
  d: '6f8b8c',
} as const;
export const LIGHT_PALETTE = {
  h: '24776e',
  m: '245d68',
  e: '276849',
  p: 'a04b6b',
  s: '866049',
  g: '5b6572',
  w: '526764',
  d: '687776',
} as const;
export type ColorRole = keyof typeof DARK_PALETTE;
export const FULL = [
  '{h}                _,',
  '{h}               /ﾉ',
  "{h}          .---'/`-----.",
  '{h}         /   / ﾉ \\     {h}\\',
  '{h}        / .ﾉﾉ /\\  ヽ    {h}\\',
  '{h}       / ﾉ ノ   ヽﾊ {p}*    {h}\\',
  '{h}      /ﾉ / ﾉヽノ ヽﾊ      {h}\\',
  '{h}      |:|{g} .---.   .---. {h}|:|',
  '{g}     ({h}|:|{g}( {e}ｨ◕ﾟ{g} )-( {e}ﾟ◕ﾐ{g} ){h}|:|{g})',
  "{h}      |:|{g} '---'   '---' {h}|:|",
  '{h}      |:| {s}({p}//       //{s}) {h}|:|',
  '{h}      \\:\\  {s}\\    ᴗ    /  {h}/:/',
  '{h}       \\_\\  {s}\\       /  {h}/_/',
  "{m}         '--'{s}╰─────╯{m}'--'",
  '{g}             .-{s}\\_/{g}-.',
  '{g}            /  {p}>o<{g}  \\',
  "{g}            '-------'",
] as const;
export const COMPACT = [
  '{h}           _,',
  '{h}          /ﾉ',
  "{h}       .-'/`--.",
  '{h}      / /ﾉ\\     {h}\\',
  '{h}     /ﾉノ ヽﾊ{p}*   {h}\\',
  '{g}    ({h}|:{g}({e}◕ﾟ{g})-({e}◕ﾟ{g}){h}:|{g})',
  '{h}     |:{s}({p}//   //{s}){h}:|',
  '{h}     \\:{s} \\  ᴗ  / {h}:/',
  "{h}      '- {s}╰───╯ {h}-'",
  '{g}        / {p}>o<{g} \\',
  "{g}        '-----'",
] as const;
export const TINY = [
  '{h}  .---.',
  '{g} ({h}|{e}o-o{h}|{g})',
  '{h}  \\{s} v {h}/',
  "{s}   '-'",
  '{g}   /{p}><{g}\\',
] as const;
export const EXPRESSIONS = [
  {
    key: 'little_smile',
    zh: '轻笑',
    en: 'Little smile',
    left: 'ｨ◕ﾟ',
    right: 'ﾟ◕ﾐ',
    mouth: 'ᴗ',
    mark: '✧',
  },
  {
    key: 'happy',
    zh: '开心',
    en: 'Happy',
    left: '/^\\',
    right: '/^\\',
    mouth: 'ᴗ',
    mark: '*',
  },
  {
    key: 'wink',
    zh: '眨眼',
    en: 'Wink',
    left: 'ｨ◕ﾟ',
    right: ' > ',
    mouth: 'ᴗ',
    mark: '☆',
  },
  {
    key: 'shy',
    zh: '害羞',
    en: 'Shy',
    left: '｡◕ ',
    right: ' ◕｡',
    mouth: 'ᴗ',
    mark: '',
  },
  {
    key: 'surprised',
    zh: '惊讶',
    en: 'Surprised',
    left: ' O ',
    right: ' O ',
    mouth: 'o',
    mark: '!',
  },
  {
    key: 'head_tilt',
    zh: '歪头',
    en: 'Head tilt',
    left: 'ｨ◕ﾟ',
    right: ' o ',
    mouth: 'ｰ',
    mark: '?',
  },
  {
    key: 'peek',
    zh: '探头',
    en: 'Peek',
    left: '◕ﾟ ',
    right: '◕ﾟ ',
    mouth: 'v',
    mark: '',
  },
  {
    key: 'smug',
    zh: '得意',
    en: 'Smug',
    left: ' - ',
    right: ' ◕ ',
    mouth: 'ᴗ',
    mark: '✧',
  },
  {
    key: 'pouting',
    zh: '气鼓鼓',
    en: 'Pouting',
    left: ' > ',
    right: ' < ',
    mouth: '3',
    mark: '!',
  },
  {
    key: 'sad',
    zh: '委屈',
    en: 'Sad',
    left: '｡◕ ',
    right: ' ◕｡',
    mouth: '~',
    mark: '',
  },
  {
    key: 'crying',
    zh: '哭泣',
    en: 'Crying',
    left: ' T ',
    right: ' T ',
    mouth: '~',
    mark: '',
  },
  {
    key: 'sleepy',
    zh: '困倦',
    en: 'Sleepy',
    left: ' - ',
    right: ' - ',
    mouth: 'o',
    mark: 'z',
  },
  {
    key: 'asleep',
    zh: '熟睡',
    en: 'Asleep',
    left: ' u ',
    right: ' u ',
    mouth: 'ｰ',
    mark: 'z Z z',
  },
  {
    key: 'excited',
    zh: '期待',
    en: 'Excited',
    left: ' ✧ ',
    right: ' ✧ ',
    mouth: 'ᴗ',
    mark: '*',
  },
  {
    key: 'dizzy',
    zh: '晕乎',
    en: 'Dizzy',
    left: ' @ ',
    right: ' @ ',
    mouth: '~',
    mark: '~',
  },
  {
    key: 'side_eye',
    zh: '小嫌弃',
    en: 'Side eye',
    left: ' ¬ ',
    right: ' ¬ ',
    mouth: 'ｰ',
    mark: '...',
  },
] as const;
export type Expression = (typeof EXPRESSIONS)[number]['key'];
export type MascotSize = 'full' | 'compact' | 'tiny';
export const SIZES = {
  full: { width: 38, height: 17 },
  compact: { width: 22, height: 11 },
  tiny: { width: 8, height: 5 },
} as const;
